export const contactPageCopy = {
  heroEyebrow: "Contact",
  heroTitle: "We’re here to help",
  heroSubtitle:
    "Questions about CKB escrow, milestones, or getting started as a client or freelancer? Send a note and we’ll route it to the right person on the team.",
  formNameLabel: "Name",
  formNamePlaceholder: "Your name",
  formEmailLabel: "Email",
  formEmailPlaceholder: "you@example.com",
  formTopicLabel: "Topic",
  formTopicEscrow: "Escrow & CKB",
  formTopicPartnership: "Partnership",
  formTopicPress: "Press",
  formTopicOther: "Other",
  formMessageLabel: "Message",
  formMessagePlaceholder: "How can we help?",
  formSubmit: "Send message",
  formSending: "Sending…",
  formSuccessTitle: "Thanks — we received your message",
  formSuccessBody: "We’ll reply by email as soon as we can. If it’s urgent, mention that in the subject line next time.",
  validationName: "Please enter your name.",
  validationEmail: "Please enter a valid email address.",
  validationMessage: "Please add a short message (at least 20 characters).",
} as const;
