export const findTalentPageCopy = {
  heroTitle: "Find talent you can trust on-chain",
  searchPlaceholder: "Search names, headlines, skills, or location…",
  searchButton: "Search",
  categoriesLabel: "Focus",
  filterAll: "All",
  resultsLabel: (n: number) => (n === 1 ? "1 freelancer" : `${n} freelancers`),
  emptyTitle: "No freelancers match that search",
  emptyBody: "Try another keyword or clear filters to see everyone available right now.",
  clearFilters: "Clear filters",
} as const;

export const freelancerDetailCopy = {
  backToTalent: "Back to talent",
  notFoundTitle: "We couldn’t find that profile",
  notFoundBody: "It may have been removed. Head back to browse available freelancers.",
  browseTalent: "Browse talent",
  tabAbout: "About",
  tabWorkHistory: "Work history",
  tabEmployment: "Employment history",
  tabSkills: "Skills",
  tabCertifications: "Certifications",
  tabEducation: "Education",
  availableNow: "Available now",
  verified: "Verified",
  jobSuccess: "Job Success",
  invite: "Invite",
  totalJobs: "Total jobs",
  rateChip: "Rate",
  languageChip: "Language",
  aboutHeading: (firstName: string) => `About ${firstName}`,
  showMore: "Show more",
  showLess: "Show less",
  playIntro: "Play intro video",
  emptyWorkHistory: "No work history yet.",
  emptyEmployment: "No employment history listed.",
  emptyCerts: "No certifications listed.",
  emptyEducation: "No education listed.",
};
